/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Auth`; params?: Router.UnknownInputParams; } | { pathname: `/doctors`; params?: Router.UnknownInputParams; } | { pathname: `/doctorsdetails`; params?: Router.UnknownInputParams; } | { pathname: `/drawer`; params?: Router.UnknownInputParams; } | { pathname: `/hospitaldetails`; params?: Router.UnknownInputParams; } | { pathname: `/hospitals`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/registeration`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/donor` | `/donor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Auth`; params?: Router.UnknownOutputParams; } | { pathname: `/doctors`; params?: Router.UnknownOutputParams; } | { pathname: `/doctorsdetails`; params?: Router.UnknownOutputParams; } | { pathname: `/drawer`; params?: Router.UnknownOutputParams; } | { pathname: `/hospitaldetails`; params?: Router.UnknownOutputParams; } | { pathname: `/hospitals`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/registeration`; params?: Router.UnknownOutputParams; } | { pathname: `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/donor` | `/donor`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/Auth${`?${string}` | `#${string}` | ''}` | `/doctors${`?${string}` | `#${string}` | ''}` | `/doctorsdetails${`?${string}` | `#${string}` | ''}` | `/drawer${`?${string}` | `#${string}` | ''}` | `/hospitaldetails${`?${string}` | `#${string}` | ''}` | `/hospitals${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/registeration${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/donor${`?${string}` | `#${string}` | ''}` | `/donor${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Auth`; params?: Router.UnknownInputParams; } | { pathname: `/doctors`; params?: Router.UnknownInputParams; } | { pathname: `/doctorsdetails`; params?: Router.UnknownInputParams; } | { pathname: `/drawer`; params?: Router.UnknownInputParams; } | { pathname: `/hospitaldetails`; params?: Router.UnknownInputParams; } | { pathname: `/hospitals`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/registeration`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/donor` | `/donor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
